//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mp3Exp.rc
//
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    123
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 124
#define IDR_MAINFRAME                   128
#define IDD_INTELLITAG_VALIDATE         130
#define IDB_LARGEICONS                  132
#define IDS_CAPTION                     136
#define IDS_OPTION_CAPTION              136
#define IDD_OPTIONPAGE1                 140
#define IDD_OPTIONPAGE2                 142
#define IDB_HOTTOOLBAR                  146
#define IDB_COLDTOOLBAR                 147
#define IDD_ABOUTPAGE1                  149
#define IDD_ABOUTPAGE2                  150
#define IDD_OPTIONPAGE3                 152
#define IDB_REBARBITMAP                 158
#define IDB_SMALL_ICONS                 160
#define IDR_AVI1                        166
#define IDS_OLE_INIT_FAILED             167
#define IDB_LOGO                        169
#define IDB_CHECK                       171
#define IDD_OPTIONPAGE4                 171
#define IDI_SYSTRAY                     177
#define IDD_DEFINE_FORMAT               178
#define IDD_OPTIONPAGE5                 179
#define IDD_RENAME                      180
#define IDD_OPTIONPAGE6                 181
#define IDD_OPTIONPAGE7                 185
#define IDD_ID3V2PAGE2                  186
#define IDB_SPLASH                      187
#define IDD_SMALL_VIEWER                188
#define IDB_COLDVIEWER                  189
#define IDD_OPTIONPAGE8                 189
#define IDB_HOTVIEWER                   190
#define IDR_MENU_VIEWER                 190
#define IDB_BANDEAU                     192
#define IDB_FILE                        193
#define IDB_PLAYLIST                    194
#define IDB_GENRE                       195
#define IDB_ARTIST                      196
#define IDB_ALBUM                       197
#define IDD_OPTIONPAGE9                 205
#define IDD_FIND                        206
#define IDD_ID3V2PAGE1                  207
#define IDD_SEARCH                      208
#define IDD_ID3V2PAGE3                  209
#define IDD_HTML_MENU                   210
#define IDD_ID3V1PAGE1                  211
#define IDR_HTML_DEFAULT                214
#define IDB_WEB_SEARCH_RESOURCES        215
#define IDB_ID3V1                       216
#define IDD_OPTIONPAGE10                218
#define IDD_OPTIONPAGE11                219
#define IDC_EDIT_TITLE                  1000
#define IDS_PLUGIN_NAME                 1000
#define IDC_EDIT_ARTIST                 1001
#define IDS_PLUGIN_VERSION              1001
#define IDC_EDIT_ALBUM                  1002
#define IDS_PLUGIN_CREDITS              1002
#define IDC_EDIT_YEAR                   1003
#define IDS_PLUGIN_AVI                  1003
#define IDC_EDIT_COMMENT                1004
#define IDC_CMB_PATH                    1006
#define IDC_EDIT_ARTIST_URL             1006
#define IDC_FINDFILES                   1007
#define IDC_CHECK_NORMALIZE             1007
#define IDC_CHECK_VALIDATE              1008
#define IDC_CMB_GENRE                   1009
#define IDC_LIST_RATING                 1010
#define IDC_BT_HOMEPAGE                 1011
#define IDC_LIST_TRACKNUM               1011
#define IDC_CHECK_FULLROW               1013
#define IDC_EDIT_TRACK                  1013
#define IDC_RADIO_PLAY                  1016
#define IDC_RADIO_ENQUEUE               1017
#define IDC_RADIO_PROPERTIES            1018
#define IDC_DISPLAY_LIMITED             1019
#define IDC_CHECK_CACHED_CATALOG        1019
#define IDC_CHECK_UNDERSCORES           1019
#define IDC_CHK_FORMAT_DEF              1019
#define IDC_CHECK_EXPORT_REINIT         1019
#define IDC_CHECK_SCAN_M3U              1019
#define IDC_CHECK_RENAME                1019
#define IDC_CHECK_SCAN_PLS              1020
#define IDC_CREDIT                      1022
#define IDC_COLUMN_LIST                 1023
#define IDC_CENTER_ALIGN                1025
#define IDC_LEFT_ALIGN                  1026
#define IDC_RIGHT_ALIGN                 1027
#define IDC_BUTTON_UP                   1028
#define IDC_BUTTON_DOWN                 1029
#define IDC_EDIT_FAVORITE_ADDRESSES     1031
#define IDC_EDIT_PLAY                   1038
#define IDC_EDIT_ENQUEUE                1039
#define IDC_EDIT_MAX_ROW                1043
#define IDC_CMB_FIELD1                  1047
#define IDC_CMB_FIELD2                  1048
#define IDC_CMB_FIELD3                  1049
#define IDC_EDIT_SEP1                   1050
#define IDC_EDIT_SEP2                   1051
#define IDC_EDIT_FORMAT_NAME            1052
#define IDC_RENAMING_PREVIEW            1057
#define IDC_LIST_FORMATS                1058
#define IDC_EDIT_SEP3                   1058
#define IDC_BT_ADD_FORMAT               1059
#define IDC_CMB_FIELD4                  1059
#define IDC_BT_MODIFY_FORMAT            1060
#define IDC_FORMAT_FREE                 1060
#define IDC_BT_DELETE_FORMAT            1061
#define IDC_FORMAT_PREDEFINED           1061
#define IDC_EDIT_NEW_NAME               1062
#define IDC_CMB_FORMATS                 1063
#define IDC_RADIO_CHOOSE_FILE           1064
#define IDC_RADIO_DEFAULT_FILE          1065
#define IDC_EDIT_EXPORT_FILE            1066
#define IDC_RADIO_FORMAT_DEFAULT        1067
#define IDC_BT_CHOOSE_EXPORT            1068
#define IDC_RADIO_FORMAT_SPECIFIC       1069
#define IDC_EDIT_EXPORT_FORMAT          1070
#define IDC_CHECK_SCAN_MP3              1076
#define IDC_VIEWER_LIST                 1078
#define IDC_COMBO_PLUGINS               1085
#define IDC_FILENAME                    1086
#define IDC_VERSION                     1087
#define IDC_CREDITS                     1088
#define IDC_LIST_ARTIST                 1089
#define IDC_LIST_ALBUM                  1090
#define IDC_EDIT_FIND                   1097
#define IDC_EDIT_LYRICS                 1098
#define IDC_BUTTON_SELECT               1099
#define IDS_FILE_PAGE_TEMPLATE          1100
#define IDC_BUTTON_PASTE                1100
#define IDC_PICTURE                     1102
#define IDC_CMB_RATING_MIN              1103
#define IDC_CHECK_LYRICS                1104
#define IDC_CHECK_PICTURE               1105
#define IDC_LIST_RESULT                 1106
#define IDC_CMB_RATING_MAX              1107
#define IDC_CMB_BITRATE_MIN             1108
#define IDC_CMB_BITRATE_MAX             1109
#define IDC_TAB                         1110
#define IDC_BT_SEARCH                   1113
#define IDC_LB_BITRATE_MIN              1114
#define IDC_LB_RATING_MIN               1115
#define IDC_LB_RATING_MAX               1116
#define IDC_LB_BITRATE_MAX              1117
#define IDC_GROUP_BITRATE               1118
#define IDC_GROUP_RATING                1119
#define IDC_GROUP_EXTEND                1120
#define IDC_LB_GENRE                    1121
#define IDC_LB_TITLE                    1122
#define IDC_LB_ARTIST                   1123
#define IDC_LB_ALBUM                    1124
#define IDC_EDIT_YEAR_MIN               1125
#define IDC_LB_YEAR                     1126
#define IDC_LB_YEAR_MIN                 1127
#define IDC_EDIT_YEAR_MAX               1128
#define IDC_LB_YEAR_MAX                 1129
#define IDC_EDIT_SEARCH                 1131
#define IDC_LB_WEB_SEARCH_RESOURCES     1133
#define IDC_LB_LOCAL                    1135
#define IDC_LB_INTERNET                 1136
#define IDC_COMBOEX_WEB_SEARCH_RESOURCES 1137
#define IDC_WEB_SEARCH_RESOURCE_DESCRIPTION 1139
#define IDC_LINK_FILEVIEW               1142
#define IDC_LINK_HELP                   1143
#define IDC_LINK_README                 1144
#define IDC_LINK_WEBSITE                1145
#define IDC_CHECK_NO_CONNECTION         1146
#define IDC_CHECK_WRITE_ID3V1_TAG       1147
#define IDC_LOWER                       1148
#define IDC_UPPER                       1149
#define IDC_PROPER                      1150
#define IDC_NOCHANGE                    1151
#define IDC_CHECK_UNDERSCORE            1152
#define IDC_CAPFIRST                    1153
#define IDC_FIELD_LIST                  1154
#define IDC_CMB_ARTIST                  1158
#define IDC_CMB_ALBUM                   1159
#define IDC_BT_NORMALIZE                1163
#define IDC_RADIO_ID3V2                 1166
#define IDC_RADIO_ID3V1                 1167
#define IDC_LABEL_WRITE_ID3V1_TAGS      1169
#define IDC_BT_YESTOALL                 1170
#define IDC_BT_CANCELALL                1171
#define IDC_RADIO_LOWER                 1178
#define IDC_RADIO_UPPER                 1179
#define IDC_RADIO_PROPER                1180
#define IDC_RADIO_UNCHANGED             1181
#define IDC_COMBO_LANGUAGES             1184
#define IDS_COLOR_SPLASHTEXT            1200
#define IDS_COLOR_LINK                  1201
#define IDS_COLOR_LISTBOX_SEL           1202
#define IDS_COLOR_VIEWTEXT              1204
#define IDS_COLOR_VIEWTEXTBG            1205
#define IDS_COLOR_VIEWBACKGROUND        1206
#define IDS_COLOR_VIEWSELECTTEXT        1207
#define IDS_COLOR_VIEWSELECTBACKGROUND  1208
#define IDS_COLOR_TREEBACKGROUND        1209
#define IDS_COLOR_HTMLMENUBACKGROUND    1210
#define IDS_COLOR_TREETEXT              1211
#define IDS_COLOR_HTMLMENUTEXT          1212
#define IDS_COLOR_HTMLMENULABEL         1213
#define IDS_COLOR_HTMLMENULABELBACKGROUND 1214
#define IDS_COLOR_HTMLMENULINK          1215
#define IDS_COLOR_CREDITSTEXT           1216
#define IDS_COLOR_CREDITSBACKGROUND     1217
#define IDS_LISTVIEW_BG_BITMAP          1300
#define IDC_ITEM1                       2001
#define IDC_ITEM2                       2002
#define IDC_ITEM3                       2003
#define IDC_ITEM4                       2004
#define IDC_ITEM5                       2005
#define IDC_ITEM6                       2006
#define IDC_ITEM7                       2007
#define IDC_ITEM8                       2008
#define IDC_ITEM9                       2009
#define ID_FILE_PLAY                    32771
#define ID_FILE_ENQUEUE                 32772
#define ID_FILE_EDIT_TAG                32773
#define ID_VIEW_ADRESSBAR               32783
#define ID_VIEW_TOOLBAR_LABELS          32784
#define ID_VIEW_OPTIONS                 32786
#define ID_DISPLAY_ALBUM                32787
#define ID_DISPLAY_ARTIST               32788
#define ID_DISPLAY_GENRE                32789
#define ID_DISPLAY_ALL                  32793
#define ID_FILE_UPDATE_SNAPSHOT         32794
#define ID_FILE_RENAME                  32795
#define ID_LISTVIEW_DROPDOWN            32796
#define ID_FILE_DELETE                  32797
#define ID_FILE_EXPORT                  32799
#define ID_FILE_EXPORT_ALL              32800
#define ID_FILE_ADD_TO_PLAYLIST         32804
#define ID_POPUP_PLAYLIST               32805
#define ID_PLAYLIST_SAVE                32808
#define ID_PLAYLIST_SAVEAS              32809
#define ID_DETAIL_DOWN                  32812
#define ID_DETAIL_UP                    32813
#define ID_FILE_BROWSE_ADDRESS          32816
#define ID_VIEWER_ARTIST                32818
#define ID_VIEWER_GENRE                 32819
#define ID_VIEWER_ALBUM                 32820
#define ID_VIEWER_PLAYLIST              32821
#define ID_VIEW_SMALL_VIEWER            32823
#define ID_VIEWER_LARGE_MODE            32824
#define ID_VIEWER_PLAY                  32825
#define ID_VIEWER_ENQUEUE               32826
#define ID_PLAYLIST_SHUFFLE             32827
#define ID_PLAYLIST_RESET               32829
#define ID_FILE_PLAYLIST_ALL            32831
#define ID_TOOLS_PLAYER                 32832
#define ID_TOOLS_NETSEARCH              32834
#define ID_FINDFIRST                    32835
#define ID_FINDNEXT                     32836
#define ID_SEARCH                       32837
#define ID_VIEW_PLAYLIST                32846
#define ID_FILE_INTELLITAG              32849
#define ID_FILE_NORMALIZE               32850
#define ID_FILE_PUBLISH                 32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1185
#define _APS_NEXT_SYMED_VALUE           210
#endif
#endif
